name: 'bq_reservations_sample'
version: '0.1.0'
config-version: 2

profile: 'default'

vars:
  RESERVATION_CONFIG:
    - tag: high_slots
      reservation: "projects/masthead-prod/locations/us/reservations/default-pipeline"
      models:
        - model.bq_reservations_sample.slots
    - tag: low_slots
      reservation: null
      models:
        - model.bq_reservations_sample.default
    - tag: on_demand
      reservation: "none"
      models:
        - model.bq_reservations_sample.on_demand
