name: 'bq_reservations_sample'
version: '0.1.0'
config-version: 2

profile: 'default'

query-comment:
  job-label: True

vars:
  RESERVATION_CONFIG:
    - tag: high_slots
      reservation: "projects/masthead-prod/locations/us/reservations/default-pipeline"
      models:
        - model_bq_reservations_sample_slots
    - tag: low_slots
      reservation: null
      models:
        - model_bq_reservations_sample_default
    - tag: on_demand
      reservation: "none"
      models:
        - model_bq_reservations_sample_on_demand
