name: 'bq_reservations_sample'
version: '0.1.0'
config-version: 2

profile: 'default'

query-comment:
  job-label: True

vars:
  RESERVATION_CONFIG:
    - tag: editions
      reservation: "projects/masthead-prod/locations/us/reservations/default-pipeline"
      models:
        - model.bq_reservations_sample.slots
    - tag: default
      reservation: null
      models:
        - model.bq_reservations_sample.default
    - tag: on_demand
      reservation: "none"
      models:
        - model.bq_reservations_sample.on_demand
        - snapshot.bq_reservations_sample.slots_ephemeral
        - snapshot.bq_reservations_sample.slots_snapshot
