default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: masthead-dev
      dataset: test
      threads: 3
      location: US
      compute_region: us-central1
      gcs_bucket: staging.masthead-dev.appspot.com
