default:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: masthead-dev
      dataset: test
      threads: 3

vars:
  RESERVATION_CONFIG:
    - tag: high_slots
      reservation: "projects/masthead-prod/locations/us/reservations/default-pipeline"
      models:
        - model.bq_reservations_sample.slots
    - tag: low_slots
      reservation: null
      models:
        - snapshot.bq_reservations_sample.slots_ephemeral
        - snapshot.bq_reservations_sample.slots_snapshot
    - tag: on_demand
      reservation: "none"
      models:
        - model.bq_reservations_sample.on_demand
        - model.bq_reservations_sample.default
