name: 'sample_setter'
version: '0.1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]


vars:
  RESERVATION_CONFIG:
    - tag: high_slots
      reservation: "projects/my-project/locations/us/reservations/high"
      models:
        - model.sample_setter.customers
        - model.sample_setter.hello
    - tag: low_slots
      reservation: null
      models: []
    - tag: on_demand
      reservation: "none"
      models:
        - model.sample_setter.analytics_model
